# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API endpoint to save achievements

Globals:
    Api:
        # API Gateway regional endpoints
        EndpointConfiguration: EDGE
        Cors:
            AllowMethods: "'*'"
            AllowHeaders: "'*'"
            AllowOrigin: "'*'"

Resources:
    PopulateAchievementStatsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: save-achievement-stats.default
            Runtime: nodejs10.x
            Timeout: 90
            CodeUri: ./dist/save-achievement-stats
            MemorySize: 128
            ReservedConcurrentExecutions: 40
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
            Tags:
                LambdaName: api-save-achievements
            Events:
                GetResource:
                    Type: Api
                    Properties:
                        Path: /{proxy+}
                        Method: any

Outputs:
    PopulateAchievementStatsApi:
        Description: URL to post achievement stats
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/achievementstats'
        Export:
            Name: PopulateAchievementStatsApi
